___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [40]:
#import libraries 
import numpy as np 

In [41]:
my_list = [1,2,3]
print(my_list)

[1, 2, 3]


In [42]:
my_list = [1,2,3]

In [43]:
np.array(my_list) #converting a list to an array

array([1, 2, 3])

In [44]:
myMatrix = [[1,2,3],
            [4,5,6],
            [7,8,9]]

In [45]:
print(myMatrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [46]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [47]:
np.arange(1,12)  #arange is used to generate array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
np.arange(3,12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
np.arange(15,70) #start, stop, step

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69])

In [51]:
np.arange(15,70,3) #start, stop, #step

array([15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63,
       66, 69])

In [52]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
np.

In [53]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
np.ones(3)

array([1., 1., 1.])

In [55]:
np.ones(10)* 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [56]:
np.ones((3,4)) #rows & columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [33]:
np.linspace(0,20,4)  #even space adds the steps then add the even means 2 

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [58]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

Creates an identity matrix

In [59]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [61]:
np.random.rand(4) #uniform distribution over 0 and 1 

array([0.94223942, 0.57683152, 0.67862804, 0.27515129])

In [64]:
np.random.randint(1,6,size=12)

array([5, 2, 1, 1, 3, 4, 2, 5, 4, 4, 3, 3])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [65]:
np.random.randn(5,5)

array([[ 2.11134391,  1.13822796,  0.43910828, -1.54960183,  1.54242974],
       [-1.11317353,  1.39560561, -1.32866038, -0.97545493,  1.25885638],
       [ 1.21891174, -0.32185751,  0.01447332,  0.9893617 , -1.05605666],
       [-0.77090541, -0.41415918,  1.06100245, -1.4750877 , -0.00888742],
       [-0.31991176,  1.89745897,  0.2925072 , -1.61975291, -1.23865588]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [30]:
np.random.randint(1,
                  100, size =10)

array([49, 47, 14, 32,  2,  3, 73, 69, 94, 17])

In [66]:
np.random.randint(1,10,5)

array([3, 2, 5, 5, 9])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [35]:
arr = np.arange(1,24)

In [36]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [53]:
arr.shape  #attributes #the rows and columns 

(23,)

###### Reshape
Returns an array containing the same data with a new shape.

In [38]:
arr.reshape(1,23)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]])

In [39]:
arr.shape

(23,)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [54]:
arr.max()

23

In [55]:
arr.min()

1

In [62]:
arr.argmax() #for location index for maximum

22

In [56]:
arr.min()

1

In [63]:
arr.argmin() #location index for minimum 

0

## Shape

Shape is an attribute that arrays have (not a method):

In [57]:
arr.shape

(23,)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [58]:
# Notice the two sets of brackets
arr.reshape(1,23) #row first, follow by columns

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]])

In [70]:
arr.shape

(23,)

In [67]:
#arr.reshape(25,1)

In [67]:
arr.reshape(1,25)

ValueError: cannot reshape array of size 23 into shape (1,25)

In [69]:
#arr.reshape(25,1)

In [63]:
arr.shape

(23,)

In [72]:
arr.reshape(5,5).shape

ValueError: cannot reshape array of size 23 into shape (5,5)

In [60]:
arr = np.arange(1,26)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [65]:
arr.shape

(5, 5)

In [62]:
arr = arr.reshape(5,5)

In [63]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### dtype

You can also grab the data type of the object in the array:

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [64]:
arr.dtype

dtype('int32')

### Great Job!